### ISSUE TITLE
Avoid tracking PDF result files in the main github draft repository

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#3318]
From #3313 :

> Separately, we should consider not tracking all the papers in the primary git repository; source checkouts of the draft are huge and growing rapidly due to this.

**Comment by jensmaurer** [comment]
@nemequ said:
> The "normal" flow would be to just keep the LaTeX in the repo and attach the PDFs (and Markdown, HTML, etc.) to the releases, preferably automatically generated and deployed by Travis.

**Comment by oss-assist** [comment]
@jensmaurer @nemequ Why the latest C++ draft on open-std.org is newer than the document available in this repo?

**Comment by oss-assist** [comment]
@jensmaurer @nemequ
Making this repo to just have the latest tex sources would be nice, since git takes care of source revisions and GitHub would take care of the PDF releases.

**Comment by oss-assist** [comment]
@jensmaurer If the whole repo is too large for you to keep track of locally, you can use the following commands to clone the very minimum quickly:
<pre>
git clone --single-branch -j 8 -b master --depth 1 https://github.com/cplusplus/draft.git
</pre>
<pre>
git fetch --depth=1
</pre>

**Comment by jensmaurer** [comment]
Editorial meeting: The purpose of the git repository is for the convenience of the editors. The suggestions do not provide additional convenience. For copies of the resulting PDF draft documents, see the public committee mailings.

**Comment by tkoeppe** [comment]
We should keep this open, and consider actually purging the PDFs from the repository. This might require something like `git filter-branch`. To be investigated.

**Comment by tkoeppe** [comment]
Editorial meeting cnt'd: If if we do a filter-branch, i.e. we rewrite the entire history, we must (in the sense of "shall") keep a record of all the old commit hashes and their corresponding new hashes. This is because we make reference to commit hashes in various places, such as commit messages and github issues. (We should also incrementally update any affected commit messages as we go along.)

**Comment by tkoeppe** [comment]
A problem with rewriting history is that we have published commit hashes in N-numbered papers (as part of Edtior's Reports).

**Comment by tkoeppe** [comment]
Idea: clone the repository into a frozen, archival location, so that the commit hashes remain in some sense valid.

**Comment by jwakely** [comment]
Isn't a branch from current master enough to preserve the hashes?

**Comment by jensmaurer** [comment]
@jwakely: Yes, but then the total repo size won't shrink (because the PDFs are still present on that other branch).

`git filter-branch --index-filter 'git rm --cached --ignore-unmatch papers/*.pdf' filtered`
removes the PDFs on a branch "filtered". Seems to work; preserves all merge-commit (which is something we might not want).

**Comment by zygoloid** [comment]
I wonder if there's anything specific to github that we can do here to preserve the old hashes. Unlike with a stock `git` repository, `git fetch` from github does *not* fetch all history: in particular, it doesn't fetch pull requests. Perhaps we could preserve the history by tracking it as a pull request?

**Comment by jensmaurer** [comment]
Usual pull requests are branches on a different repo clone (e.g. mine), so they don't show up for a "git fetch" on the main repo. For motions branches (which are, by convention, pushed to the main repo), I do see them when I do a "git fetch".

**Comment by zygoloid** [comment]
> Usual pull requests are branches on a different repo clone (e.g. mine), so they don't show up for a "git fetch" on the main repo. For motions branches (which are, by convention, pushed to the main repo), I do see them when I do a "git fetch".

That's not entirely accurate. When you create a pull request, the commits of the pull request become visible in the destination repository too. For example, consider unmerged pull request https://github.com/cplusplus/draft/pull/3496; the head commit of that (0095e0bb) is visible in the main repository too: https://github.com/cplusplus/draft/commit/0095e0bb87bf2e63e7c6664dd0fd68a89ebea9c1

You can also see this from the command line: `git fetch origin pull/3496/head` will fetch commit 0095e0bb from the cplusplus/draft repository, despite it never having been pushed to any branch there.

**Comment by zygoloid** [comment]
In fact, it looks like the github model is that internally there is only one repository for an original repository plus all of its forks, irrespective of pull requests. For example, consider b1b8d3296d04fb6e751db86e09e34e54a0c262f5, which was committed to my fork of cplusplus/draft, and has never been part of any pull request. Nonetheless, it is visible in this repository via the github UI, and is available on the command line via `git fetch origin b1b8d3296d04fb6e751db86e09e34e54a0c262f5`.

**Comment by jensmaurer** [comment]
Looks like https://github.com/newren/git-filter-repo/ is the tool for the job, including keeping old hash references valid and transparently rewriting commit messages.

**Comment by jensmaurer** [comment]
This looks pretty close to what we want to achieve:

```
git-filter-repo \
        --replace-refs update-and-add  \
        --invert-paths --path-glob "papers/n*.pdf" --path-glob "papers/N*.pdf" \
        --path-rename papers/N3338.html:papers/n3338.html \
        --path-rename papers/N3377.html:papers/n3377.html \
        --path-rename papers/N3486.html:papers/n3486.html \
        --path-rename papers/N3798.html:papers/n3798.html \
        --path-rename papers/N3938.html:papers/n3938.html
```
It prunes the repo from (currently) 432 MB to 48 MB, adds replace refs pointing from the old commit hashes to the new ones (so that references in editor's reports stay valid) and updates commit hashes in commit messages (e.g. "Revert abcdef").

**Comment by jensmaurer** [comment]
Editorial meeting 2021-05-28: Create a clickable list with links to all working drafts we ever had. "git rm" the PDF files so that "git clone --depth" can be used to omit the PDFs, in the future.

**Comment by tkoeppe** [comment]
@Eelis We will probably have to force-push the main branch to do the above filtering, and we'll rename the default branch. Please do let us know if that poses any problems for you!

**Comment by Eelis** [comment]
> @Eelis We will probably have to force-push the main branch to do the above filtering, and we'll rename the default branch. Please do let us know if that poses any problems for you!

No problems, do what needs to be done.

**Comment by tkoeppe** [comment]
@Eisenwave voila, we have an issue about this.

**Comment by eisenwave** [comment]
@tkoeppe ah yeah. The problem I had is that VScode search would find wording occurrences in old drafts under `papers/*.html`.

It's very annoying when you're looking for certain uses of a term, and what you discover are ancient working drafts.

**Comment by tkoeppe** [comment]
Wait, to repeat and to be clear, the working draft has never been published as HTML, and only ever as a PDF. Can you give an example of what you're finding that you wish you didn't find?

**Comment by eisenwave** [comment]
If you search for subclause names (to either find the definition or `iref`s, you would also discover commit messages in editor's reports in HTML format, since commit messages contain subclause names.

The same applies to any sort of technical terms that are mentioned in the commit messages, though I can't name any striking example off the top of my head.

**Comment by tkoeppe** [comment]
Yes, you are searching the editors' reports, undoubtedly. So can we agree that working drafts are not relevant to your point?

**Comment by eisenwave** [comment]
Yeah, I think so.

**Comment by jwakely** [comment]
> If you search for subclause names (to either find the definition or `iref`s, you would also discover commit messages in editor's reports in HTML format, since commit messages contain subclause names.
> 
> The same applies to any sort of technical terms that are mentioned in the commit messages, though I can't name any striking example off the top of my head.

Wait, why are you searching commit messages to find definitions of terms? 

Why don't `git grep` or `git log -S` work?

**Comment by jwakely** [comment]
And restrict those commands to `source/*.tex` if needed.

**Comment by eisenwave** [comment]
> Wait, why are you searching commit messages to find definitions of terms?

I'm just searching all files in the GUI with Ctrl+Shift+F, I'm not grepping via CLI. The commit messages are copied into HTML source of the editor's reports.

It's possible to restrict global search to a certain directory, but I'm not sure if VSCode remembers your choice per workspace, so you'd always end up searching a bunch of unnecessary stuff by default.

Of course, one could argue "just add the filter when you search then", but one could also argue "I shouldn't have to do that."

**Comment by tkoeppe** [comment]
There is a remaining question here whether we should actually delete the existing PDFs from head. This doesn't reduce the size of the full repository, but I think if you do some kind of depth-limited checkout, this might eventually allow for smaller checkouts.
