### ISSUE TITLE
[lex.ppnumber] should also include user-defined-integer-literal and user-defined-floating-point-literal

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#5188]
[lex.ppnumber] p1
> Preprocessing number tokens lexically include all integer-literal tokens ([lex.icon]) and all floating-point-literal tokens ([lex.fcon]).

Doesn't it also include all user-defined-integer-literal tokens and all user-defined-floating-point-literal tokens? The same issue is also in [lex.ppnumber]p2.

**Comment by jensmaurer** [comment]
Yes, _pp-number_ also includes those user-defined literals and many more things that are not valid phase 7 tokens. It says "includes", which doesn't imply the meaning of "and nothing else".

Regarding p2, the statement is correct; user-defined literal tokens cannot be successfully converted to integer-literals or floating-point literals.

**Comment by xmh0511** [comment]
I would expect that [lex.ppnumber] can state the complete stuff it should have covered. Looks like: 
> Preprocessing number tokens lexically include all integer-literal tokens ([lex.icon]), all floating-point-literal tokens ([lex.fcon]), all user-defined-integer-literal tokens and all user-defined-floating-point-literal tokens([lex.ext]). 
>
> A preprocessing number does not have a type or a value; it acquires both after a successful conversion to one of the following:   
>> - an integer-literal token
>> - a floating-point-literal token
>> - a user-defined-integer-literal token
>> - a user-defined-floating-point-literal token

**Comment by jensmaurer** [comment]
If we want to improve something here, I think we should instead wholly change [lex.ppnumber] to clearly say to what things it can convert for phase 7, and avoid "include" and similar vague words.

Oh, and _operator-or-punctuator_ should lose `and`, `bitand`, etc. because that's a parsing ambiguity with _identifier_.

**Comment by xmh0511** [comment]
> 

Agree. I think it's not only [lex.ppnumber] but also other preprocessing token clauses. Since [lex.phases] p7 says
> Each preprocessing token is converted into a token ([lex.token]). The resulting tokens are syntactically and semantically analyzed and translated as a translation unit. 

However, we never explicitly restrict what kind of preprocessing tokens could convert to the what kind of tokens. Maybe, we could define that for every preprocessing token. Such as:
> a pp-number can be potentially converted to one of the following:
>> - an integer-literal token
>> - a floating-point-literal token
>> - a user-defined-integer-literal token
>> - a user-defined-floating-point-literal token
>
> an identifier preprocessing token can be potentially converted to one of the following:
>> - identifier
>> - keyword  

In short, we need to give the range of which tokens the preprocessing token could convert to.

**Comment by RedBeard0531** [comment]
A while back I started working on [a paper](https://isocpp.org/files/papers/D2180R0.html) to clean up _pp-number_ by having   _pp-token_  just directly include the relevant numeric literal tokens. Unfortunately, that breaks a non-trivial amount of real-world code that does terrible things like this:

```cpp
#define HEX(tok) 0x ## tok
#define ID(tok) id_ ## tok

HEX(0bad) // 0x0bad is a valid hex literal
ID(09) // id_09 is a valid identifier
```

That meant that I needed to completely redo the paper which I lost the motivation to do. I'm not trying to discourage someone from fixing _pp-number_ (I still think it should be fixed), just warning that it is more subtle than it initially seems.

**Comment by xmh0511** [comment]
IMO, pp-number has a wider extent than the actual numeric literal token, which means the latter is a subset of the former since the former is not necessary to be a valid numeric literal token after converting to the token, such as `0xe+foo` as shown in the standard. Based on this logic, I think it is not simply to *clean up pp-number by having pp-token just directly include the relevant numeric literal tokens.*

**Comment by AlisdairM** [comment]
I am not sure I see a problem here.  A pp-number matches a wide variety of text that is not valid in phase 7, but might be useful throughout phase 4, as noted for various token concatenation examples.  When preprocessing tokens are converted to tokens ta the start of phase 7, no valid conversion is found and the program is ill-formed.

We might use more clarity that preprocessor tokens might not have a valid conversion to tokens, making a program ill-formed, but that would be a bigger  issue than just pp-numbers.

**Comment by RedBeard0531** [comment]
> I am not sure I see a problem here.

The motivating example for me was that `static_assert(0xFE+1 == 0xFF);` should compile. I would find it hard to explain to someone why it doesn't without a very deep sigh and an apology. It doesn't today because `0xFE+1` is parsed as a single pp-number token (rather than `0xFE` `+` `1`) which then becomes an invalid token in phase 7. An alternative way to fix this would be to allow a single pp-number to be re-lexed into multiple tokens rather than requiring a 1:1 mapping from pp-token to token. But that may be an even bigger can of worms...

**Comment by AlisdairM** [comment]
But unless I am missing something, 0xFE+1  is also not a user-defined-integer-literal, so the proposed solution would still not work?  Or does the issue need a new title?

**Comment by AlisdairM** [comment]
Looking at your concern for expanding specific kinds of pp-numbers, perhaps a new _literal-expression_ token for phase 7, that would allow preprocessor-tokens to expand to valid literal expression, but not to more exotic expressions involving names?  Either way, it is looking very much like a core request and not an editorial issue.

**Comment by jensmaurer** [comment]
Maybe there's room for an improvement to the C++ language in the treatment of `0xFE+1` here, but such is not in the scope of an editorial change.
